#!/usr/bin/env python3
"""Generate read-only Docker mounts for ACLI-registered matters.

The Gateway cannot see a newly registered matter merely because ACLI can.  This
small restart-time adapter turns the ACLI matter registry into extra bind mounts
without putting a broad home-directory mount into the Gateway container.
"""

from __future__ import annotations

import json
import os
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
REGISTRY_CANDIDATES = (
    Path(os.environ.get("ACLI_MATTERS_REGISTRY", "")),
    REPO_ROOT.parent / "development_channel" / "acli_matters.json",
    Path("/Users/ed/King/clawd_2/development_channel/acli_matters.json"),
)
BASE_OVERRIDE = REPO_ROOT / "docker-compose.override.yml"
GENERATED_OVERRIDE = REPO_ROOT / ".voice_gateway_matter_mounts.override.yml"
EXCLUDED_MATTER_FOLDERS = {"nemoclaw_nc"}


def _registry_path() -> Path | None:
    for candidate in REGISTRY_CANDIDATES:
        if str(candidate) and candidate.is_file():
            return candidate
    return None


def _matter_paths() -> list[Path]:
    registry_path = _registry_path()
    if registry_path is None:
        return []
    try:
        registry = json.loads(registry_path.read_text(encoding="utf-8"))
    except (OSError, ValueError, TypeError):
        return []
    raw_matters = registry.get("matters", [])
    if not isinstance(raw_matters, list):
        return []

    paths: list[Path] = []
    for raw in raw_matters:
        path = Path(str(raw or "").strip()).expanduser()
        if path.name.casefold() in EXCLUDED_MATTER_FOLDERS:
            continue
        if not path.is_dir() or not (path / "acli" / "matter.json").is_file():
            continue
        if path not in paths:
            paths.append(path)
    return paths


def generate() -> Path:
    existing = BASE_OVERRIDE.read_text(encoding="utf-8") if BASE_OVERRIDE.is_file() else ""
    missing = [path for path in _matter_paths() if str(path) not in existing]

    lines = [
        "# Generated by scripts/sync_gateway_matter_mounts.py; do not edit.",
        "services:",
        "  voice-channel:",
        "    volumes:",
    ]
    for path in missing:
        # JSON quoting is valid YAML quoting and preserves spaces in volume paths.
        bind = f"{path}:{path}:ro"
        lines.append(f"      - {json.dumps(bind)}")
    GENERATED_OVERRIDE.write_text("\n".join(lines) + "\n", encoding="utf-8")
    return GENERATED_OVERRIDE


if __name__ == "__main__":
    print(generate())
